sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: MssOBxbMMJD6jTJRZnjPXEPOoqysDNvrdX5yvfbNr6RDe0uRPtQ8wvFKEM2R2qCRRwcT5J+sAZpne/Q9bu2A78OXNYWziZu7BMKIvIzoGeT/zc/dK6tMl+or/G03B+xEIecNnYwynbAN7QMZ3TGdBuBudQH6O+2KaI+v15BpjeXGRS9WmdYo1nvDqVm8bN2W+k10bDgk0wUrd7RPTSlv7dFNi2gfz9p6jnVQDTkCBdPh5ihL/ths1BCHqhTddsi5p0TiSWa1rc+0xFrzuW3L3B+YJRYkS1jJoX1j8ocgfGoGoGBL7jr8yL1426K1u1UXly8ZhInBtck8qE1S/bwQHuKWSCvgIT74pXSBLPY/x7VedQQCrJPQRxt329cegHHnplG+RMHQ/jo3tNE9t4p5hL6p7QaG2kqQfrwcHwcNgUcHTnTkBhkuuMGPzVdafPCkglx+avUckQyueDwwjFGAt5VK8lBeqkmsX5ndsHiRJ5qKw8OPBMSOh0Qgd38Lk0+DWewxmfqOzOqM+dJHeqZt41owBmM6aZZSVsz0CET+EdUggtw/9ymG7C7S66EQ4qNqNzLxLBRJ6T/tz9RKoG3lgXv2vdh6bPCRPzTCVNeoos4/sM6PuKPg19y2IScwkow59uZRqoXdHiJLZYVrJ7ng66FZCOVNSBlcUsfKJqenhn4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/As-We-Were-Saying_3106
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy